name: Cache

on:
  push:
    branches:
      - cache

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Connect to Cachix
        uses: cachix/cachix-action@v14
        with:
          name: openxai
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Upload base derivation to Cachix
        run: nix build ./example#nixosConfigurations.container.config.system.build.toplevel --accept-flake-config --print-out-paths | cachix push openxai

      - name: Upload cuda derivation to Cachix
        run: nix build ./example/cuda#nixosConfigurations.container.config.system.build.toplevel --accept-flake-config --print-out-paths | cachix push openxai
